//! Stored voiceprints: the roster of people the recognizer knows, and the ways to correct it.
//!
//! A voiceprint is not a row of its own — it is the embedding on a meeting's cluster
//! (`clusters.centroid`). Removing one therefore clears that column rather than deleting anything:
//! the cluster, its name binding, and every past transcript survive, and only cross-meeting
//! recognition stops.

use axum::extract::State;
use axum::http::StatusCode;
use axum::routing::{delete, get, patch};
use axum::Router;
use uuid::Uuid;

use hearsay_db::queries;

use crate::error::{ApiError, ApiResult};
use crate::extract::{Json, Path, Query};
use crate::routes::{reexport, validated_name, Pagination};
use crate::schema::{IdentityRead, IdentityRename, Page, VoiceprintRead};
use crate::state::AppState;

/// Routes served under the `/api` prefix (token-gated by the caller).
pub fn router() -> Router<AppState> {
    Router::new()
        .route("/voiceprints", get(list_voiceprints))
        .route("/voiceprints/{cluster_id}", delete(delete_voiceprint))
        .route("/identities/{id}", patch(rename_identity))
        .route("/identities/{id}/voiceprint", delete(forget_voice))
}

/// The voice roster: people who have a stored voiceprint, with all of their samples.
///
/// Lists only people who **have** an embedding. Someone named in a meeting that was never refined
/// has no centroid and is therefore absent — they are still a known person on `GET /api/identities`,
/// just not a voice. Clearing someone's last sample drops them from this list, so `sample_count` is
/// always at least 1.
///
/// `active_count` is the subset recognition actually uses (a sample counts only once its name was
/// set by hand), so `active_count: 0` means "saved, matching nothing yet". `dimension` is the
/// embedding length (256 from FluidAudio) — and samples of different lengths never match
/// each other.
#[utoipa::path(
    get, path = "/api/voiceprints", tag = "voiceprints",
    params(("page" = Option<u32>, Query), ("page_size" = Option<u32>, Query)),
    responses((status = 200, body = Page<VoiceprintRead>, description = "A page of people with stored voiceprints")),
)]
pub(crate) async fn list_voiceprints(
    State(state): State<AppState>,
    Query(pagination): Query<Pagination>,
) -> ApiResult<Json<Page<VoiceprintRead>>> {
    let window = pagination.resolve(50, 200);
    // Counts people with a voiceprint, not identities: someone merely named in a meeting that was
    // never refined has no embedding, so they are not part of this roster.
    let total = queries::count_voiceprint_people(&state.pool).await?;
    let people = queries::list_voiceprints(&state.pool, window.limit, window.offset).await?;
    Ok(Json(window.page_of(total, people)))
}

/// Rename a person everywhere.
///
/// Renames the identity and relabels every segment bound to it, across every meeting, in one
/// transaction, then re-exports each affected `transcript.md`. Generated notes are **not**
/// regenerated — they are model output rather than derived rows, so they keep the old name until
/// regenerated by hand.
///
/// A name collision is a conflict, never a silent identity merge. Re-applying the current name is a
/// no-op `200`.
#[utoipa::path(
    patch, path = "/api/identities/{id}", tag = "voiceprints",
    params(("id" = Uuid, Path)),
    request_body = IdentityRename,
    responses(
        (status = 200, body = IdentityRead, description = "The renamed person"),
        (status = 404, description = "No such person"),
        (status = 409, description = "Another person already holds that name"),
        (status = 422, description = "Blank name, or over 255 characters"),
    ),
)]
pub(crate) async fn rename_identity(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
    Json(body): Json<IdentityRename>,
) -> ApiResult<Json<IdentityRead>> {
    let name = validated_name(&body.display_name, "display_name")?;
    let (identity, meeting_ids) = match queries::rename_identity(&state.pool, id, name).await? {
        queries::RenameIdentityOutcome::Renamed {
            identity,
            meeting_ids,
        } => (identity, meeting_ids),
        queries::RenameIdentityOutcome::NotFound => {
            return Err(ApiError::NotFound("person not found"))
        }
        queries::RenameIdentityOutcome::NameTaken => {
            return Err(ApiError::Conflict(
                "another person already uses that name".into(),
            ))
        }
    };
    // This rename relabelled segments across every meeting the person appears in, so each of those
    // transcripts needs re-rendering. Sequential and best-effort: the writes are cheap (a read plus
    // one atomic file write each) and SQLite is single-writer, so fanning out would only queue.
    for meeting_id in meeting_ids {
        reexport(&state, meeting_id, "identity rename").await;
    }
    Ok(Json(identity.into()))
}

/// Forget one voice sample.
///
/// Clears that cluster's centroid and nothing else: the cluster, the name binding, and every past
/// transcript survive, and only future recognition changes. Idempotent.
#[utoipa::path(
    delete, path = "/api/voiceprints/{cluster_id}", tag = "voiceprints",
    params(("cluster_id" = Uuid, Path)),
    responses(
        (status = 204, description = "Centroid cleared (or already absent)"),
        (status = 404, description = "No such cluster"),
    ),
)]
pub(crate) async fn delete_voiceprint(
    State(state): State<AppState>,
    Path(cluster_id): Path<Uuid>,
) -> ApiResult<StatusCode> {
    if !queries::clear_cluster_centroid(&state.pool, cluster_id).await? {
        return Err(ApiError::NotFound("voiceprint not found"));
    }
    Ok(StatusCode::NO_CONTENT)
}

/// Forget a person's voice entirely.
///
/// Clears every centroid stored for that person, including unlocked ones — otherwise an unlocked
/// sample would re-enter the candidate set as soon as its cluster was renamed. Names, locks, and
/// past transcripts are untouched; only future recognition stops.
#[utoipa::path(
    delete, path = "/api/identities/{id}/voiceprint", tag = "voiceprints",
    params(("id" = Uuid, Path)),
    responses(
        (status = 204, description = "All of that person's centroids cleared"),
        (status = 404, description = "No such person"),
    ),
)]
pub(crate) async fn forget_voice(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> ApiResult<StatusCode> {
    if !queries::forget_identity_voice(&state.pool, id).await? {
        return Err(ApiError::NotFound("person not found"));
    }
    Ok(StatusCode::NO_CONTENT)
}
