/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_folders"];
        put?: never;
        post: operations["create_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_folder"];
        options?: never;
        head?: never;
        patch: operations["rename_folder"];
        trace?: never;
    };
    "/api/folders/{id}/parent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["reparent_folder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_identities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["rename_identity"];
        trace?: never;
    };
    "/api/identities/{id}/voiceprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["forget_voice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_meetings"];
        put?: never;
        post: operations["start_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_meeting"];
        put?: never;
        post?: never;
        delete: operations["delete_meeting"];
        options?: never;
        head?: never;
        patch: operations["update_meeting"];
        trace?: never;
    };
    "/api/meetings/{id}/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assign_meeting_folder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/keep-recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * "Keep recording": reset the active meeting's inactivity clock so a present-but-quiet user is not
         *     nudged again or auto-ended. A no-op for any meeting that is not the current recording session
         *     (404) — there is no clock to reset. Idempotent and cheap; the client calls it when the user
         *     dismisses the "still recording?" prompt.
         */
        post: operations["keep_recording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_notes"];
        put?: never;
        post: operations["generate_notes"];
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["edit_notes"];
        trace?: never;
    };
    "/api/meetings/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause the live meeting's capture (the "Pause" control): recording + transcription stop and the
         *     timeline freezes with no gap until resumed. A 404 for any meeting that is not the current
         *     recording session. Idempotent (pausing an already-paused meeting is a no-op 204).
         */
        post: operations["pause_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/rediarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rediarize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused meeting's capture. A 404 for any meeting that is not the current recording
         *     session. Idempotent (resuming a non-paused meeting is a no-op 204).
         */
        post: operations["resume_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open this meeting's recordings folder (audio, transcript, notes, meeting.json) in the OS file
         *     manager — the per-meeting analog of the Settings "Reveal data folder" action, reusing the same
         *     `open`-in-Finder helper. Runs in the core (a native process in the user's login session), reached
         *     over the same-origin HTTP API. Failures surface the reason (not a generic 500) so a broken reveal
         *     is diagnosable.
         */
        post: operations["reveal_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_segments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["edit_segment"];
        trace?: never;
    };
    "/api/meetings/{id}/segments/{segment_id}/speaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reassign_segment_speaker"];
        trace?: never;
    };
    "/api/meetings/{id}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_speakers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/speakers/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["rename_speaker"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/speakers/{cluster_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["merge_speakers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop_meeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/user-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_user_notes"];
        put: operations["save_user_notes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download_status"];
        put?: never;
        post: operations["start_download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_models"];
        post?: never;
        delete: operations["reset_models"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_recording"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open the effective recordings directory in the OS file manager. Runs in the core (a native
         *     process in the user's login session), reached over the same-origin HTTP API the rest of Settings
         *     uses — the desktop shell's Tauri `invoke()` is not reliably reachable from the webview's remote
         *     loopback origin, so the "Reveal data folder" button routes here instead. On failure the reason is
         *     surfaced to the client (not collapsed to a generic 500) so a broken reveal is diagnosable.
         */
        post: operations["reveal_output_dir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_speakers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_storage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/storage/compress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_archive"];
        put?: never;
        /**
         * Run the archival pass now instead of waiting for the periodic sweep.
         * @description Returns immediately with the starting snapshot and does the work in the background -- a backlog
         *     can take a minute of CPU, far longer than a request should hold. The UI polls the GET above.
         *     Honors the effective age threshold, so pressing the button never archives a meeting the user's
         *     own setting says is still too recent; it does not require the automatic sweep to be enabled,
         *     since pressing it is an explicit instruction.
         */
        post: operations["start_archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["read_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voiceprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_voiceprints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voiceprints/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_voiceprint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Read-only build/runtime facts for the About panel (`protocol_version` is the core's IPC
         *     frame-protocol constant; a mismatch with the helper's reported copy signals version drift).
         */
        AboutInfo: {
            app_version: string;
            database_path: string;
            environment: string;
            /** Format: int32 */
            protocol_version: number;
        };
        /**
         * @description Progress of the audio-archival pass, whether started by the Settings button or the periodic
         *     sweep. Polled by the UI while `running`; the counters describe the current pass, or the last one
         *     once it has finished. Read-only.
         */
        ArchiveState: {
            /** Format: int32 */
            compressed: number;
            /**
             * Format: int32
             * @description Meetings processed so far.
             */
            done: number;
            /** Format: int32 */
            failed: number;
            /** Format: int64 */
            reclaimed_bytes: number;
            running: boolean;
            /**
             * Format: int32
             * @description Meetings this pass will process.
             */
            total: number;
        };
        /**
         * @description A capture-health frame (not a transcript line): the named stream is delivering digital silence —
         *     exactly-zero samples, which a working microphone never produces — so the UI warns that the mic is
         *     muted or dead. Without this the failure is invisible, because ASR does not return nothing for
         *     silence, it hallucinates text. Mirrors the orchestrator's `CaptureHealthEvent` on the wire.
         */
        CaptureHealthEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`CaptureHealthEvent`] (`"capture_health"`).
             * @enum {string}
             */
            kind: "capture_health";
            /**
             * @description Whether a capture stream is delivering audio (`ok`) or nothing at all (`silent`).
             * @enum {string}
             */
            state: "ok" | "silent";
            /** @description The affected stream; only `me` (the mic) is monitored. */
            stream: string;
        };
        /**
         * @description A capture-state frame (not a transcript line): the meeting was paused or resumed (the "Pause"
         *     control). Lets a live view freeze the timer/waveform on pause and resume them; also snapshotted on
         *     WebSocket connect so a window reopened mid-pause reflects it. Mirrors the orchestrator's
         *     `CaptureStateEvent` on the wire.
         */
        CaptureStateEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`CaptureStateEvent`] (`"capture_state"`).
             * @enum {string}
             */
            kind: "capture_state";
            /**
             * @description Whether live capture is paused or actively running.
             * @enum {string}
             */
            state: "paused" | "active";
        };
        /** @description One downloadable notes model in the in-app catalog (the internal repo/file/sha are not exposed). */
        CatalogEntry: {
            context: string;
            id: string;
            /** @description Whether this model's file already resolves in the models dir (downloaded). */
            installed: boolean;
            license: string;
            name: string;
            note: string;
            recommended: boolean;
            /** Format: int64 */
            size_bytes: number;
        };
        /** @description Request body for starting a catalog download: the catalog `id` to fetch. */
        DownloadRequest: {
            id: string;
        };
        /** @description A snapshot of the (single, at-a-time) model download, polled by the UI like sidecar readiness. */
        DownloadState: {
            /** Format: int64 */
            downloaded_bytes: number;
            /** @description A human-readable detail (an error reason, or the resolved path when ready). */
            message?: string | null;
            /** @description The catalog id being downloaded (or last downloaded), if any. */
            model_id?: string | null;
            status: components["schemas"]["DownloadStatus"];
            /** Format: int64 */
            total_bytes: number;
        };
        /**
         * @description Where a download is in its lifecycle.
         * @enum {string}
         */
        DownloadStatus: "idle" | "downloading" | "verifying" | "ready" | "error";
        /**
         * @description Create a folder. `name` is validated non-empty, <= 255 chars; `parent_id` nests it under an
         *     existing folder (omit or `null` for a root folder).
         */
        FolderCreate: {
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
        };
        /**
         * @description An organizational folder for meetings (a node in the nested folder tree). `parent_id` is `null`
         *     for a root folder.
         */
        FolderRead: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Reparent a folder. `parent_id` is the new parent, or `null` to move it to the root. Validated: a
         *     non-null `parent_id` must exist and must not be the folder itself or one of its descendants (which
         *     would create a cycle).
         */
        FolderReparent: {
            /** Format: uuid */
            parent_id?: string | null;
        };
        /** @description Rename a folder. `name` replaces the folder's display name (validated non-empty, <= 255 chars). */
        FolderUpdate: {
            name: string;
        };
        /** @description A known cross-meeting person (offered as a rename suggestion). */
        IdentityRead: {
            display_name: string;
            email?: string | null;
            /** Format: uuid */
            id: string;
        };
        /** @description Rename a person everywhere they appear. */
        IdentityRename: {
            display_name: string;
        };
        /**
         * @description An audio-level frame (not a transcript line): the recent RMS amplitude of a capture stream,
         *     broadcast a few times a second so the UI can drive a live input waveform. Ephemeral — never
         *     persisted or replayed to a new subscriber. Mirrors the orchestrator's `LevelEvent` on the wire.
         */
        LevelEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`LevelEvent`] (`"level"`).
             * @enum {string}
             */
            kind: "level";
            /**
             * Format: float
             * @description Root-mean-square amplitude of the recent audio, normalized f32 samples (`0.0..~1.0`).
             */
            rms: number;
            /** @description The stream this level is for (`me` or `them`). */
            stream: string;
        };
        /** @description Start a meeting. `title` defaults to a timestamp-derived name when omitted. */
        MeetingCreate: {
            title?: string | null;
        };
        /**
         * @description File a meeting under a folder. `folder_id` is the target folder, or `null` to un-file (move it
         *     back to the root/"Unfiled" list). Validated: a non-null `folder_id` must reference an existing
         *     folder.
         */
        MeetingFolderAssign: {
            /** Format: uuid */
            folder_id?: string | null;
        };
        /**
         * @description A meeting's generated notes for the API: the model's reply as verbatim Markdown `content`, and
         *     which model produced them. The prompt template dictates the note's format, so there is no
         *     structured summary/action-item shape.
         */
        MeetingNotesRead: {
            content: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Whether these notes have been manually edited (drives the "edited" badge + the regenerate
             *     overwrite warning).
             */
            edited: boolean;
            model: string;
            /**
             * @description Whether the transcript changed after these notes were generated/edited — i.e. the notes may be
             *     out of date. Computed at read time (a mutating response sets it `false`).
             */
            stale: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A meeting row for the API. */
        MeetingRead: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            ended_at?: string | null;
            /**
             * @description The on-disk recordings-directory name (not an organizational folder). To move a meeting
             *     between user folders, use `folder_id`.
             */
            folder: string;
            /**
             * Format: uuid
             * @description The organizational [`FolderRead`] this meeting is filed under, or `null` when unfiled.
             */
            folder_id?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            started_at: string;
            status: components["schemas"]["MeetingStatus"];
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Lifecycle state of a meeting (lowercase on the wire): `recording` while live, `refining` while the
         *     post-stop refine + transcript write run in the background, then `finalized`.
         * @enum {string}
         */
        MeetingStatus: "recording" | "refining" | "finalized";
        /** @description Rename a meeting. `title` replaces the meeting's display title (validated non-empty, <= 255 chars). */
        MeetingUpdate: {
            title: string;
        };
        /** @description The notes-model catalog + where downloads land, for the Settings > Models picker. */
        ModelCatalog: {
            items: components["schemas"]["CatalogEntry"][];
            models_dir: string;
        };
        /**
         * @description Models: the offline-refine whisper model path plus the optional local-LLM notes step (enable +
         *     its GGUF model). Editable section; each effective value is the stored override, else the config
         *     default. Live transcription is the FluidAudio/ANE sidecars and is not configured here.
         */
        ModelSettings: {
            /**
             * @description Generate meeting notes at stop (the optional local-LLM notes step).
             *     `#[serde(default)]` so a `models` row written before notes existed still deserializes.
             */
            notes_enabled?: boolean;
            /** @description GGUF model path for the notes step; empty until one is downloaded or chosen. */
            notes_model?: string;
            /**
             * @description User-editable prompt template for the notes step (its `{transcript}` placeholder is filled
             *     with the finalized transcript). Empty means "use the built-in default"
             *     (`ModelsInfo::default_notes_prompt`). `#[serde(default)]` so a `models` row written before the
             *     prompt existed still deserializes.
             */
            notes_prompt?: string;
            refine_model: string;
        };
        /**
         * @description Read-only model facts shown alongside the editable models section: the bundled/config defaults
         *     (reset targets) and whether each effective model file currently resolves on disk.
         */
        ModelsInfo: {
            default_notes_model: string;
            /**
             * @description The built-in default notes prompt template (the reset target + the effective value when the
             *     editable `notes_prompt` is empty).
             */
            default_notes_prompt: string;
            default_refine_model: string;
            notes_model_exists: boolean;
            refine_model_exists: boolean;
        };
        /** @description A manual notes edit: replace the Markdown `content`. Validated at the boundary (length-bounded). */
        NotesEdit: {
            content: string;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_FolderRead: {
            items: {
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uuid */
                parent_id?: string | null;
                /** Format: date-time */
                updated_at: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_IdentityRead: {
            items: {
                display_name: string;
                email?: string | null;
                /** Format: uuid */
                id: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_MeetingRead: {
            items: {
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                ended_at?: string | null;
                /**
                 * @description The on-disk recordings-directory name (not an organizational folder). To move a meeting
                 *     between user folders, use `folder_id`.
                 */
                folder: string;
                /**
                 * Format: uuid
                 * @description The organizational [`FolderRead`] this meeting is filed under, or `null` when unfiled.
                 */
                folder_id?: string | null;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                started_at: string;
                status: components["schemas"]["MeetingStatus"];
                title: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_SearchHit: {
            items: {
                /** Format: uuid */
                meeting_id: string;
                meeting_status: components["schemas"]["MeetingStatus"];
                meeting_title: string;
                /** Format: uuid */
                segment_id: string;
                snippet: string;
                speaker_label: string;
                /** Format: double */
                start_s: number;
                /** Format: date-time */
                started_at: string;
                stream: components["schemas"]["Stream"];
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_SegmentRead: {
            items: {
                /** Format: uuid */
                cluster_id?: string | null;
                /**
                 * @description Whether this segment has been manually edited — its text or its speaker assignment (drives the
                 *     "edited" badge + the discard-on-refine warning).
                 */
                edited: boolean;
                /** Format: double */
                end_s: number;
                /** Format: uuid */
                id: string;
                speaker_label: string;
                /** Format: double */
                start_s: number;
                stream: components["schemas"]["Stream"];
                text: string;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_SpeakerRead: {
            items: {
                /**
                 * Format: uuid
                 * @description The cluster id.
                 */
                id: string;
                /** Format: uuid */
                identity_id?: string | null;
                /** @description The bound identity's name, else `"Speaker {ordinal}"`. */
                label: string;
                locked: boolean;
                /** Format: int64 */
                ordinal: number;
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Paginated list envelope used by every list endpoint (`{ total, page, page_size, items }`). */
        Page_VoiceprintRead: {
            items: {
                /**
                 * Format: int64
                 * @description The subset that recognition actually uses (locked, with an embedding).
                 */
                active_count: number;
                display_name: string;
                email?: string | null;
                /** Format: uuid */
                identity_id: string;
                /**
                 * Format: date-time
                 * @description Start of the most recent meeting a sample came from.
                 */
                last_heard?: string | null;
                /**
                 * Format: int64
                 * @description Stored samples, whether or not they are recognition candidates.
                 */
                sample_count: number;
                samples: components["schemas"]["VoiceprintSampleRead"][];
            }[];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /**
         * @description Live TCC permission status probed from the capture helper (not a stored preference). Each field
         *     is `granted` / `denied` / `undetermined`, or `unknown` when the helper is unavailable.
         *     `helper_version` is the connected helper's build (`None` when unavailable).
         */
        PermissionsInfo: {
            accessibility: string;
            audio_capture: string;
            calendar: string;
            helper_available: boolean;
            helper_version?: string | null;
            microphone: string;
            screen_recording: string;
        };
        /**
         * @description An inactivity nudge (not a transcript line): the meeting has had no detected speech for
         *     `silent_seconds`, so the UI shows a "still recording?" banner (Stop / Keep recording). If silence
         *     continues to the end threshold the meeting auto-ends. Mirrors the orchestrator's `PromptEvent` on
         *     the wire.
         */
        PromptEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`PromptEvent`] (`"prompt"`).
             * @enum {string}
             */
            kind: "prompt";
            /** Format: int64 */
            silent_seconds: number;
        };
        /**
         * @description Recording & privacy — the audio-retention switch (keep one WAV per meeting for playback + the
         *     post-meeting refine) plus the inactivity watchdog: independently toggle the "still recording?"
         *     prompt and the silence auto-end, with the silence thresholds in minutes (the prompt fires at
         *     `inactivity_prompt_minutes`, the auto-end at `inactivity_end_minutes`, which must be the larger
         *     when both are on). Editable section; a request body and part of [`SettingsRead`].
         */
        RecordingSettings: {
            inactivity_auto_end_enabled: boolean;
            /** Format: int32 */
            inactivity_end_minutes: number;
            inactivity_prompt_enabled: boolean;
            /** Format: int32 */
            inactivity_prompt_minutes: number;
            record: boolean;
        };
        /**
         * @description A backfill signal (not a transcript line): the broadcast buffer dropped events for a lagged
         *     subscriber, so the persisted transcript is ahead of this live stream. On receipt the client
         *     refetches persisted segments rather than diverging.
         */
        ResyncEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`ResyncEvent`] (`"resync"`).
             * @enum {string}
             */
            kind: "resync";
        };
        /**
         * @description One transcript-search hit for the API: the matched segment with enough meeting context to render
         *     and navigate to it. `snippet` is the matched text with each match wrapped in the private-use
         *     sentinels U+E000/U+E001, which the client swaps for highlight markup.
         */
        SearchHit: {
            /** Format: uuid */
            meeting_id: string;
            meeting_status: components["schemas"]["MeetingStatus"];
            meeting_title: string;
            /** Format: uuid */
            segment_id: string;
            snippet: string;
            speaker_label: string;
            /** Format: double */
            start_s: number;
            /** Format: date-time */
            started_at: string;
            stream: components["schemas"]["Stream"];
        };
        /**
         * @description A manual transcript edit: replace a segment's `text`. Validated at the boundary (non-empty,
         *     length-bounded).
         */
        SegmentEdit: {
            text: string;
        };
        /** @description A transcript segment for the API. */
        SegmentRead: {
            /** Format: uuid */
            cluster_id?: string | null;
            /**
             * @description Whether this segment has been manually edited — its text or its speaker assignment (drives the
             *     "edited" badge + the discard-on-refine warning).
             */
            edited: boolean;
            /** Format: double */
            end_s: number;
            /** Format: uuid */
            id: string;
            speaker_label: string;
            /** Format: double */
            start_s: number;
            stream: components["schemas"]["Stream"];
            text: string;
        };
        /**
         * @description Reassign a single Them line to a different speaker. Provide exactly one of: `cluster_id` (an
         *     existing cluster in the meeting) or `display_name` (a person by name — reuses that identity's
         *     cluster in the meeting if it has one, else creates a new locked speaker).
         */
        SegmentSpeakerAssign: {
            /** Format: uuid */
            cluster_id?: string | null;
            display_name?: string | null;
        };
        /**
         * @description The full editable settings, one field per panel/section. `storage_info` and `about` are
         *     read-only context (not editable sections).
         */
        SettingsRead: {
            about: components["schemas"]["AboutInfo"];
            models: components["schemas"]["ModelSettings"];
            models_info: components["schemas"]["ModelsInfo"];
            recording: components["schemas"]["RecordingSettings"];
            speakers: components["schemas"]["SpeakerSettings"];
            storage: components["schemas"]["StorageSettings"];
            storage_info: components["schemas"]["StorageInfo"];
        };
        /** @description Combine two of a meeting's speakers: the cluster in the path is folded into `into`. */
        SpeakerMerge: {
            /**
             * Format: uuid
             * @description The surviving cluster, in the same meeting.
             */
            into: string;
        };
        /** @description A diarization cluster within a meeting, with its resolved display label. */
        SpeakerRead: {
            /**
             * Format: uuid
             * @description The cluster id.
             */
            id: string;
            /** Format: uuid */
            identity_id?: string | null;
            /** @description The bound identity's name, else `"Speaker {ordinal}"`. */
            label: string;
            locked: boolean;
            /** Format: int64 */
            ordinal: number;
        };
        /** @description Rename a cluster to a person (binds + locks; relabels that speaker's segments). */
        SpeakerRename: {
            display_name: string;
        };
        /**
         * @description Speaker diarization: re-diarize each meeting at finalize (`auto_refine`) + the cosine at/above
         *     which a refined speaker is auto-matched to a person named in a prior meeting.
         */
        SpeakerSettings: {
            auto_refine: boolean;
            /** Format: double */
            recognition_threshold: number;
        };
        /**
         * @description A warm-up status frame (not a transcript line): a `warming` snapshot on connect for a cold start
         *     and a `ready` transition once the sidecars finish, so the UI shows a "preparing" notice instead
         *     of a silent gap.
         */
        StatusEvent: {
            /**
             * @description The constant `kind` discriminant marking a [`StatusEvent`] (`"status"`), distinct from a
             *     transcript line's `partial`/`final` so the client routes it off the transcript path.
             * @enum {string}
             */
            kind: "status";
            /**
             * @description Whether the live transcription sidecars are still loading their models (`warming`) or have
             *     finished and are serving (`ready`).
             * @enum {string}
             */
            state: "warming" | "ready";
        };
        /**
         * @description Live engine readiness for the UI to gate "Start" on. `sidecars_ready` is `true` once the
         *     pre-warmed transcription sidecars have loaded their models (so a new meeting transcribes
         *     immediately) and `false` while they are still loading after launch.
         */
        StatusInfo: {
            sidecars_ready: boolean;
        };
        /** @description Read-only storage facts shown alongside the editable storage section. */
        StorageInfo: {
            database_path: string;
            /** Format: int64 */
            meeting_count: number;
            output_dir: string;
            /** Format: int64 */
            tracked_bytes: number;
            /**
             * Format: int64
             * @description Bytes still held in uncompressed `audio.wav` files — what archiving would shrink ~3x.
             */
            uncompressed_bytes: number;
        };
        /**
         * @description Storage: the default root new meetings are written under (existing meetings keep their stamped
         *     location), plus the audio-archival policy — once a finalized meeting is `compress_after_days`
         *     old, its `audio.wav` is re-encoded as lossless FLAC (~3x smaller, bit-identical, so playback and
         *     re-diarization are unaffected). Editable section; a request body and part of [`SettingsRead`].
         */
        StorageSettings: {
            /**
             * Format: int32
             * @description Days after a meeting ends before its audio is archived.
             */
            compress_after_days: number;
            /**
             * @description Archive finalized meetings' audio as lossless FLAC. Deliberately NOT `#[serde(default)]`:
             *     the PUT full-replaces the section, so a body omitting this would silently switch archival
             *     off rather than leave it alone. Required means a partial write is a 422 instead.
             */
            compress_audio: boolean;
            output_dir: string;
        };
        /**
         * @description Which capture channel a segment came from.
         * @enum {string}
         */
        Stream: "me" | "them";
        /**
         * @description A live transcript line pushed to the meeting WebSocket: a `partial` (interim, speaker-less for
         *     Them) or a `final` (persisted, with its resolved `speaker_label`).
         */
        TranscriptEvent: {
            /** Format: double */
            end_s: number;
            /**
             * @description The `kind` discriminant on a live [`TranscriptEvent`]: a pre-diarization `partial` (streamed, not
             *     persisted) or a persisted `final`. Mirrors the orchestrator's `SegmentKind` on the wire.
             * @enum {string}
             */
            kind: "partial" | "final";
            speaker_label: string;
            /** Format: double */
            start_s: number;
            stream: components["schemas"]["Stream"];
            text: string;
        };
        /**
         * @description A meeting's user-authored "My notes" body (free-form text typed during the meeting). `body` is
         *     empty when the user has typed none yet; `updated_at` drives the "autosaved" indicator.
         */
        UserNotesRead: {
            body: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description An autosave of the user's "My notes" body. Length-bounded at the boundary (reject over-large
         *     payloads as 422 rather than letting them reach the DB / the on-disk export).
         */
        UserNotesWrite: {
            body: string;
        };
        /**
         * @description A person in the stored-voiceprint roster, with every voice sample kept for them (newest meeting
         *     first). Only people who actually have an embedding appear, so `sample_count` is always >= 1;
         *     clearing someone's last sample drops them from the roster.
         */
        VoiceprintRead: {
            /**
             * Format: int64
             * @description The subset that recognition actually uses (locked, with an embedding).
             */
            active_count: number;
            display_name: string;
            email?: string | null;
            /** Format: uuid */
            identity_id: string;
            /**
             * Format: date-time
             * @description Start of the most recent meeting a sample came from.
             */
            last_heard?: string | null;
            /**
             * Format: int64
             * @description Stored samples, whether or not they are recognition candidates.
             */
            sample_count: number;
            samples: components["schemas"]["VoiceprintSampleRead"][];
        };
        /** @description One stored voiceprint: the voice embedding kept on a single meeting's cluster. */
        VoiceprintSampleRead: {
            /**
             * Format: int64
             * @description Embedding length: 256 on macOS (FluidAudio), 192 on Windows (sherpa). Samples of different
             *     lengths never match each other.
             */
            dimension: number;
            /**
             * Format: uuid
             * @description The cluster carrying the embedding — a voiceprint has no id of its own.
             */
            id: string;
            /**
             * @description Whether the name on this cluster was set by hand. Only locked samples are recognition
             *     candidates in later meetings.
             */
            locked: boolean;
            /** Format: uuid */
            meeting_id: string;
            meeting_title: string;
            /** Format: date-time */
            started_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_folders: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FolderRead"];
                };
            };
        };
    };
    create_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reparent_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderReparent"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_identities: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IdentityRead"];
                };
            };
        };
    };
    rename_identity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityRename"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forget_voice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_meetings: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MeetingRead"];
                };
            };
        };
    };
    start_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assign_meeting_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingFolderAssign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    keep_recording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingNotesRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingNotesRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotesEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingNotesRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pause_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rediarize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SpeakerRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resume_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reveal_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_segments: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SegmentRead"];
                };
            };
        };
    };
    edit_segment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentEdit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reassign_segment_speaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentSpeakerAssign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_speakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SpeakerRead"];
                };
            };
        };
    };
    rename_speaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerRename"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    merge_speakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerMerge"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SpeakerRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stop_meeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_user_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserNotesRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_user_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserNotesWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserNotesRead"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalog"];
                };
            };
        };
    };
    download_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadState"];
                };
            };
        };
    };
    start_download: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadState"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SearchHit"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    update_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSettings"];
                };
            };
        };
    };
    read_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsInfo"];
                };
            };
        };
    };
    update_recording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordingSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSettings"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reveal_output_dir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_speakers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerSettings"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_storage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageSettings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageSettings"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveState"];
                };
            };
        };
    };
    start_archive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveState"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusInfo"];
                };
            };
        };
    };
    list_voiceprints: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VoiceprintRead"];
                };
            };
        };
    };
    delete_voiceprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
