# cargo-deny license policy (https://embarkstudios.github.io/cargo-deny/). Encodes the CLAUDE.md
# open-license gate: only permissive licenses are allowed (MIT / BSD / Apache-2.0 and equivalents);
# copyleft families (GPL / AGPL / LGPL / MPL / EUPL / SSPL / CC-BY-SA) are denied by omission
# (`version = 2` treats any unlisted license as a failure). Checked by `make licenses`.
#
# NOTE: cargo-deny was not installed in the environment this file was authored in, so the allow
# list is a best-effort match for the current dependency tree. If `cargo deny check licenses`
# reports an unlisted *permissive* license, add its SPDX id here; do not add a copyleft id.

[licenses]
version = 2
confidence-threshold = 0.9
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "BSL-1.0",
]
