"""baseline: meetings and segments

Revision ID: 7e2c0680d390
Revises: 
Create Date: 2026-06-26 09:25:23.400136
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7e2c0680d390'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('recording', 'finalized', name='meetingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('stream', sa.Enum('me', 'them', name='stream', native_enum=False, length=32), nullable=False),
    sa.Column('speaker_label', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_meeting_start', ['meeting_id', 'start_s'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_meeting_start')

    op.drop_table('segments')
    op.drop_table('meetings')
    # ### end Alembic commands ###
