"""speaker clusters and identities

Revision ID: a69ee62a795b
Revises: 7e2c0680d390
Create Date: 2026-06-26 14:32:49.561551
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a69ee62a795b'
down_revision: str | None = '7e2c0680d390'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('clusters',
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('centroid', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'ordinal', name='uq_clusters_meeting_ordinal')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_segments_cluster_id', 'clusters', ['cluster_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_segments_cluster_id', type_='foreignkey')
        batch_op.drop_column('cluster_id')

    op.drop_table('clusters')
    op.drop_table('identities')
    # ### end Alembic commands ###
